about:
  name: NSE Options Configuration File
  description: |
    NSE Options is a web application that provides a simple interface to view and analyze NSE options data. The
    configuration file is used to set the application settings - like the header contents, default URL settings and
    other relevant informations.
  version: 1.0.0

config:
  # default settings, can be overridden by the user by providing the same structure
  # else, the application will use these settings as default for the application
  header:
    accept-language: en-US,en;q=0.9,en-IN;q=0.8
    accept-encoding: gzip, deflate, br, zstd

    # ! this value will periodically update as per the website - to check this::
    # open browser > inspect element > network tab > refresh the page > check the request headers
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
